cmake_minimum_required(VERSION 3.16)
find_package(ASC REQUIRED)
project(conv_3d_backprop_filter_direct LANGUAGES ASC CXX)
set(CMAKE_CXX_STANDARD 17)
add_executable(conv_3d_backprop_filter op_host/conv_3d_backprop_filter.asc)
target_include_directories(conv_3d_backprop_filter PRIVATE op_host op_kernel "$ENV{ASCEND_HOME_PATH}/include")
target_link_directories(conv_3d_backprop_filter PRIVATE "$ENV{ASCEND_HOME_PATH}/lib64" "$ENV{ASCEND_HOME_PATH}/aarch64-linux/lib64")
target_link_libraries(conv_3d_backprop_filter PRIVATE tiling_api register platform unified_dlog dl m graph_base ascendcl ascendc_runtime)
target_compile_options(conv_3d_backprop_filter PRIVATE $<$<COMPILE_LANGUAGE:ASC>:--npu-arch=dav-2201>)
