cmake_minimum_required(VERSION 3.16)
find_package(ASC REQUIRED)
project(depthwise_conv_2d_direct LANGUAGES ASC CXX)
set(CMAKE_CXX_STANDARD 17)

add_executable(depthwise_conv_2d op_host/depthwise_conv_2d.asc)
target_include_directories(depthwise_conv_2d PRIVATE op_host op_kernel)
target_link_libraries(depthwise_conv_2d PRIVATE tiling_api register platform unified_dlog dl m graph_base ascendcl ascendc_runtime)
target_link_directories(depthwise_conv_2d PRIVATE "$ENV{ASCEND_HOME_PATH}/lib64" "$ENV{ASCEND_HOME_PATH}/aarch64-linux/lib64")
target_compile_options(depthwise_conv_2d PRIVATE $<$<COMPILE_LANGUAGE:ASC>:--npu-arch=dav-2201>)
